#!/usr/bin/env python3
"""
GRUDA Node — Image to C Array Converter
Converts PNG/GIF images to RGB565 C header files for ESP32 + LVGL.

Usage:
  # Convert boot logo PNG (resized to 240x100)
  python img_to_c.py logo.png --name grudge_logo --width 240 --height 100

  # Convert gold coin GIF (all frames, 80x80 each)
  python img_to_c.py coin.gif --name coin_frame --width 80 --height 80 --gif

  Output: .h file with PROGMEM arrays ready for LVGL lv_img_dsc_t
"""

import sys
import struct
import argparse
from pathlib import Path

try:
    from PIL import Image, ImageEnhance, ImageOps
except ImportError:
    print("Install Pillow: py -m pip install Pillow")
    sys.exit(1)


def rgb888_to_rgb565(r, g, b):
    """Convert 24-bit RGB to 16-bit RGB565 (ILI9341 byte-swapped)."""
    rgb565 = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
    # Byte-swap for ILI9341 (LV_COLOR_16_SWAP = 1)
    return ((rgb565 >> 8) & 0xFF) | ((rgb565 & 0xFF) << 8)


def prepare_image(img, width, height, fit_mode, dither, brightness, contrast, saturation, sharpness):
    """Resize/process image before RGB565 conversion."""
    img = img.convert("RGB")

    if fit_mode == "cover":
        img = ImageOps.fit(img, (width, height), method=Image.LANCZOS)
    elif fit_mode == "contain":
        img = ImageOps.contain(img, (width, height), method=Image.LANCZOS)
        canvas = Image.new("RGB", (width, height), (0, 0, 0))
        off_x = (width - img.width) // 2
        off_y = (height - img.height) // 2
        canvas.paste(img, (off_x, off_y))
        img = canvas
    else:
        img = img.resize((width, height), Image.LANCZOS)

    if brightness != 1.0:
        img = ImageEnhance.Brightness(img).enhance(brightness)
    if contrast != 1.0:
        img = ImageEnhance.Contrast(img).enhance(contrast)
    if saturation != 1.0:
        img = ImageEnhance.Color(img).enhance(saturation)
    if sharpness != 1.0:
        img = ImageEnhance.Sharpness(img).enhance(sharpness)

    if dither:
        img = img.quantize(colors=256, method=Image.FASTOCTREE, dither=Image.FLOYDSTEINBERG).convert("RGB")

    return img


def image_to_rgb565(img, width, height, fit_mode, dither, brightness, contrast, saturation, sharpness):
    """Resize/process and convert PIL Image to RGB565 byte array."""
    img = prepare_image(img, width, height, fit_mode, dither, brightness, contrast, saturation, sharpness)
    data = []
    for y in range(height):
        for x in range(width):
            r, g, b = img.getpixel((x, y))
            data.append(rgb888_to_rgb565(r, g, b))
    return data


def write_c_header(name, frames, width, height, out_path):
    """Write C header file with PROGMEM arrays."""
    with open(out_path, "w") as f:
        f.write(f"/* Auto-generated by GRUDA img_to_c.py */\n")
        f.write(f"/* {len(frames)} frame(s), {width}x{height} RGB565 */\n")
        f.write(f"#ifndef GRUDA_IMG_{name.upper()}_H\n")
        f.write(f"#define GRUDA_IMG_{name.upper()}_H\n\n")
        f.write(f"#include <pgmspace.h>\n#include <lvgl.h>\n\n")
        f.write(f"#define {name.upper()}_W {width}\n")
        f.write(f"#define {name.upper()}_H {height}\n")
        f.write(f"#define {name.upper()}_FRAMES {len(frames)}\n\n")

        for idx, frame_data in enumerate(frames):
            suffix = f"_{idx}" if len(frames) > 1 else ""
            arr_name = f"{name}{suffix}"
            f.write(f"static const uint16_t {arr_name}[] PROGMEM = {{\n")
            for i, px in enumerate(frame_data):
                if i % 12 == 0:
                    f.write("    ")
                f.write(f"0x{px:04X},")
                if i % 12 == 11:
                    f.write("\n")
            f.write(f"\n}};\n\n")

        # LVGL image descriptor — C++ compatible (no nested designated initializers)
            f.write(f"static const lv_img_dsc_t {arr_name}_dsc = {{\n")
            f.write(f"    {{ LV_IMG_CF_TRUE_COLOR, 0, 0, {width}, {height} }},\n")
            f.write(f"    {width * height * 2},\n")
            f.write(f"    (const uint8_t*){arr_name}\n")
            f.write(f"}};\n\n")

        # Frame pointer array for GIFs
        if len(frames) > 1:
            f.write(f"static const lv_img_dsc_t* {name}_frames[] = {{\n")
            for idx in range(len(frames)):
                f.write(f"    &{name}_{idx}_dsc,\n")
            f.write(f"}};\n\n")

        f.write(f"#endif /* GRUDA_IMG_{name.upper()}_H */\n")

    size_kb = out_path.stat().st_size / 1024
    print(f"Written {out_path} ({size_kb:.1f} KB, {len(frames)} frames)")


def main():
    parser = argparse.ArgumentParser(description="Convert images to ESP32 C arrays")
    parser.add_argument("input", help="Input PNG or GIF file")
    parser.add_argument("--name", required=True, help="C variable name prefix")
    parser.add_argument("--width", type=int, required=True, help="Output width")
    parser.add_argument("--height", type=int, required=True, help="Output height")
    parser.add_argument("--gif", action="store_true", help="Extract all GIF frames")
    parser.add_argument("--max-frames", type=int, default=24, help="Max GIF frames")
    parser.add_argument("--fit", choices=["stretch", "cover", "contain"], default="stretch",
                        help="Resize mode")
    parser.add_argument("--dither", action="store_true", help="Apply dithering before RGB565 conversion")
    parser.add_argument("--brightness", type=float, default=1.0, help="Brightness multiplier")
    parser.add_argument("--contrast", type=float, default=1.0, help="Contrast multiplier")
    parser.add_argument("--saturation", type=float, default=1.0, help="Saturation multiplier")
    parser.add_argument("--sharpness", type=float, default=1.0, help="Sharpness multiplier")
    parser.add_argument("--out", default=None, help="Output .h path")
    args = parser.parse_args()

    img = Image.open(args.input)
    frames = []

    if args.gif and hasattr(img, "n_frames") and img.n_frames > 1:
        step = max(1, img.n_frames // args.max_frames)
        for i in range(0, img.n_frames, step):
            if len(frames) >= args.max_frames:
                break
            img.seek(i)
            frames.append(image_to_rgb565(
                img.copy(),
                args.width,
                args.height,
                args.fit,
                args.dither,
                args.brightness,
                args.contrast,
                args.saturation,
                args.sharpness,
            ))
        print(f"Extracted {len(frames)} frames from {img.n_frames} total (step={step})")
    else:
        frames.append(image_to_rgb565(
            img,
            args.width,
            args.height,
            args.fit,
            args.dither,
            args.brightness,
            args.contrast,
            args.saturation,
            args.sharpness,
        ))

    out_path = Path(args.out) if args.out else Path(f"include/img_{args.name}.h")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    write_c_header(args.name, frames, args.width, args.height, out_path)


if __name__ == "__main__":
    main()
